### ISSUE TITLE
Module does not provide an export named 'vueI18n'

### ISSUE THREAD

**Issue by Hardaker587** [intlify/nuxt3#86]
Framework: Nuxt3 RC-8

Reproduction link:  [https://stackblitz.com/edit/intlify-nuxt3-minimal-reproduction](https://stackblitz.com/edit/intlify-nuxt3-minimal-reproduction)

When running nuxt dev or nuxt build I am getting the following error:

``` bash
ERROR  The requested module '@intlify/vite-plugin-vue-i18n' does not provide an export named 'vueI18n' 
import { vueI18n } from '@intlify/vite-plugin-vue-i18n';
^^^^^^^                                                            
```

This more than likely seems related to the version of @intlify/vite-plugin-vue-i18n because this all worked a few days ago, and is now unfortunately breaking all builds.

**Comment by robotpapier** [comment]
Hi,
same here.
I don't get the message on anotehr project where @intlify/vue-i18n-loader version is 9.2.0-beta.40 though.

I have this error with version 9.3.0-beta.1

when I list dependencies of @intlify/nuxt3@0.2.3 I have :
 ├─ @intlify/shared@beta
│  ├─ @intlify/vite-plugin-vue-i18n@next
│  ├─ @intlify/vue-i18n-loader@next

is it possible maybe to install a specific version instead of the latest?

**Comment by Hardaker587** [comment]
I highly appreciate you fixing this so quickly!
